### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/lua/lib/liblua.5.3.dylib

### ISSUE THREAD

**Issue by liushawulan** [xtin/TeleFred#5]
Reason: image not found.

i found this article, https://stackoverflow.com/questions/27172680/dyld-library-not-loaded-usr-local-lib-liblua-5-1-5-dylib, and tried several times. however, it still runs error. for example, i reinstalled the telegram-cli, and installed lua@5.3. Just don't know why.

thanks.

**Comment by m0rtyn** [comment]
Same problem.
Logs:
```bash
19:36:32.576] Logging Started...
[19:36:35.050] TeleFred[Script Filter] Queuing argument ''
[19:36:35.173] TeleFred[Script Filter] Script with argv '(null)' finished
[19:36:35.175] ERROR: TeleFred[Script Filter] Code 1: dyld[24566]: Library not loaded: /usr/local/opt/lua/lib/liblua.5.3.dylib
  Referenced from: /Users/martyns0n/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AE9A52D1-39D8-4A7D-B518-7B285DC80F8B/telegram-cli
  Reason: tried: '/usr/local/opt/lua/lib/liblua.5.3.dylib' (no such file), '/usr/local/lib/liblua.5.3.dylib' (no such file), '/usr/lib/liblua.5.3.dylib' (no such file), '/usr/local/Cellar/lua/5.4.2/lib/liblua.5.3.dylib' (no such file), '/usr/local/lib/liblua.5.3.dylib' (no such file), '/usr/lib/liblua.5.3.dylib' (no such file)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "telefred.py", line 103, in handle_history
    update_chats()  # update the list of chats once - time consuming
  File "telefred.py", line 60, in update_chats
    chats = telegram("dialog_list")
  File "telefred.py", line 37, in telegram
    p = subprocess.check_output(['./telegram-cli', '--json', '-R', '-D', '-e', msg], universal_newlines=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['./telegram-cli', '--json', '-R', '-D', '-e', 'dialog_list']' returned non-zero exit status -6
```

**Comment by duongdev** [comment]
Same problem!

**Comment by olegkron** [comment]
Same.
